"use strict";
let obj;
let obj1;
obj1 = { name: "ylw" };
let obj2;
obj2 = { name: 'ylw', age: 123 };
let obj3;
obj3 = { name: "ylw", age: false, sex: true };
let arr;
arr = [12, 32,];
let arr1;
arr1 = [123];
